items:
  invisibility-tincture:
    max-uses: 6
    max-cauldron-level: 3

  disable-end-crystal: true
  disable-tnt: false
  disable-tnt-minecart: true

npc:
  villager-search-radius: 48
  villager-sprinting-speed: 0.6
  villager-walk-speed: 0.5
  villager-amount-restock: 2
  villager-station:
    text-display:
      offset-x: 0.5
      offset-y: 1.25
      offset-z: 0.5